import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Yanone_Kaffeesatz } from 'next/font/google';
import { Container } from '@mui/material';

import './styles/globals.scss';
import ThemeRegistry from './themes/ThemeRegistry';
import Header from './components/header/Header';
import Footer from './components/footer/Footer';

const playfair = Yanone_Kaffeesatz({
  subsets: ['latin'],
  variable: '--font-playfair',
});

const geistSans = Geist({
  subsets: ['latin'],
  variable: '--font-geist-sans',
});

const geistMono = Geist_Mono({
  subsets: ['latin'],
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta content="initial-scale=1, width=device-width" name="viewport" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable}`}
      >
        <ThemeRegistry>
          <Header />
          <Container component={'main'} maxWidth="lg">
            {children}
          </Container>
          <Footer />
        </ThemeRegistry>
      </body>
    </html>
  );
}
